### ISSUE TITLE
Benefits of having multiple api definitions as opposed to injecting endpoints into a single apiSlice?

### ISSUE THREAD

**Issue by Aleinbanger** [wpcodevo/JWT_Authentication_React#2]
Thank you for your great tutorial! I have a question though. Why did you choose to have multiple api definitions? Can I implement this kind of auth the way it's recommended in the [docs](https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced#injecting-endpoints)? Is there a difference in behavior? 

> RTK Query supports splitting out endpoint definitions with apiSlice.injectEndpoints(). That way, we can still have a single API slice with a single middleware and cache reducer, but we can move the definition of some endpoints to other files. This enables code-splitting scenarios, as well as co-locating some endpoints alongside feature folders if desired.

**Comment by wpcodevo** [comment]
Having multiple API definitions is a matter of personal preference.
